### ISSUE TITLE
Page has strange view

### ISSUE THREAD

**Issue by xgrommx** [wenkokke/sf#1]
@wenkokke Hello! After all procedures and when I run it I got strange view of page.
![stlcprop properties of stlc 2018-01-12 23-45-59](https://user-images.githubusercontent.com/1499594/34896557-ec30efec-f7f2-11e7-9bec-10404cbecf41.png)

How can I fix it?

**Comment by wenkokke** [comment]
Hey @xgrommx ! Could you be more specific? The image you've posted is not quite high-resolution enough to see what is going on, and "executing the procedures" isn't all that specific either—do you mean the build script, or the Agda functions, or?

**Comment by xgrommx** [comment]
@wenkokke I got it after commands `make` and `make server`. I can provide whole page if it will be needed.

**Comment by wenkokke** [comment]
Hey @xgrommx, did you encounter any errors during `make`? Right now, the instructions on how to host the code are mostly there for people who are developing this. I'll refine them a bit in the future.
