### ISSUE TITLE
Wrong formatted code in the page?

### ISSUE THREAD

**Issue by jonaprieto** [wenkokke/sf#2]
After following the instructions I got this visiting: http://127.0.0.1:4000/sf/Naturals

![image](https://user-images.githubusercontent.com/1428088/35331882-3c7587a0-0109-11e8-9d9a-05a380e3adbb.png)

And there are other parts/pages with the same problem.

**Comment by wenkokke** [comment]
I can't reproduce this, although I'm seeing some other issues right now. I think this is mostly due to bugs in my agda2html script.

**Comment by jonaprieto** [comment]
It's working now, I tested every page
